# Reasoning prompts for different versions
v0:
  template: |
    Solve the following problem step by step. 
    
    PROBLEM:
    {question}

aime:
  template: |
    Solve the following AIME problem. All answers are integers ranging from 0 to 999, inclusive.  Report your answer in \boxed{} format.
    
    PROBLEM:
    {question}